### ISSUE TITLE
🐛[BUG]Select组件在自定义组件中，无法正常下拉

### ISSUE THREAD

**Issue by srszzw** [ant-design/pro-flow#106]
### 🐛 bug 描述
Select组件在自定义节点中，无法正常下拉

**Comment by ModestFun** [comment]
在你的自定义节点的类名中，加入'nodrag' 这个类名，就可以捕获到该节点中内容的 click 事件了。

<img width="402" alt="image" src="https://github.com/user-attachments/assets/ead14c38-eacb-4b75-a8e8-752028704258">
<img width="207" alt="image" src="https://github.com/user-attachments/assets/a4cbbe62-c496-4c8d-b1fd-85d9281b8554">

**Comment by srszzw** [comment]
> 在你的自定义节点的类名中，加入'nodrag' 这个类名，就可以捕获到该节点中内容的 click 事件了。
> 
> <img alt="image" width="402" src="https://private-user-images.githubusercontent.com/61576426/353354957-ead14c38-eacb-4b75-a8e8-752028704258.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMjk3MDAsIm5iZiI6MTcyMjMyOTQwMCwicGF0aCI6Ii82MTU3NjQyNi8zNTMzNTQ5NTctZWFkMTRjMzgtZWFjYi00Yjc1LWE4ZTgtNzUyMDI4NzA0MjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA4NTAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YTExYWM4OTNiYzUxZWY5MzkwZDk3NDI5Nzk0ZDc4ODBhNjIwY2ViNDk3MWIwMzRlYmNlZTU4YWViODUyYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BKfiQ0lx-YxSzDcG5n0fbj_yZ12zzJ9Cs99S6g0N_EU"> <img alt="image" width="207" src="https://private-user-images.githubusercontent.com/61576426/353355025-a4cbbe62-c496-4c8d-b1fd-85d9281b8554.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMjk3MDAsIm5iZiI6MTcyMjMyOTQwMCwicGF0aCI6Ii82MTU3NjQyNi8zNTMzNTUwMjUtYTRjYmJlNjItYzQ5Ni00YzhkLWIxZmQtODVkOTI4MWI4NTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA4NTAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMTk1Yjg0YjkxZWIzMzZjOWQzNmRmNzkzNWVkNWFmMzNjMTc1ODkyMDYzYTZjYzFmMjg3NDM1YTVjZmI0YjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MmZZmlL8Tn7kobAHOZG5XUFyEKNHIFTx1NTn9RWqz4s">

那这样还能拖拽吗？
我的解决办法是，通过onfoucs和onchange事件来控制下拉的打开和关闭，可以封装成自定义组件：
`import React from 'react';
import { Select } from 'antd';
import { useState } from 'react';
interface FlowSelectProps {
    onChange: (value: string) => void;
    option:{value:string,label:string}[]
    defaultValue?:string
    disabled?:boolean
}

const FlowSelect: React.FC<FlowSelectProps> = ({ onChange,option,defaultValue,disabled }) => {
    const [open, setOpen] = useState(false);
    const handleSelectChange = (value: string) => {
        onChange(value);
    };
    return (
        <Select
            disabled={disabled}
            defaultValue={defaultValue}
            options={option}
            open={open}
            onFocus={() => {setOpen(true);}}
            onChange={(value)=>{setOpen(false);handleSelectChange(value)}} />
    );
};

export default FlowSelect;`
