### ISSUE TITLE
🧐[问题] 这个图书馆是 "reactflow"复制吗？

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/pro-flow#109]
这个图书馆是 "反应流 "复制吗？其用法与 react-flow 非常相似，还是说 reactflow 是该库的基础？

**Comment by arvinxx** [comment]
后者，我们基于react-flow构建了更加业务的使用场景

**Comment by xXAvoraXx** [comment]
感谢，开发一个能够与 react-flow 的付费功能竞争的免费解决方案是必要的。
