### ISSUE TITLE
🧐[我该如何才能参与到这个项目？]

### ISSUE THREAD

**Issue by 985563349** [ant-design/pro-flow#38]
### 🧐 问题描述

这是个非常棒的项目，请问我该如何才能参与到项目的建设？

**Comment by ModestFun** [comment]
可以先扫码加入我们的官方群
![1702973038962](https://github.com/ant-design/pro-flow/assets/61576426/47a6a15c-2d23-4e24-8b3f-a39ba5f52eff)
