### ISSUE TITLE
🐛[BUG]

### ISSUE THREAD

**Issue by kostosReservit** [ant-design/pro-flow#61]
Hello! I have encountered an issue when rendering the <FlowView> component, facing the following problem:
chunk-MKLIEGNN.js?v=1e762b64:3318 Uncaught TypeError: Cannot read properties of undefined (reading 'zh_CN')
at @ant-design_pro-flow.js?v=c67f97d6:256307:79
Version 0.21.0
I will attach screenshots below.
![image](https://github.com/ant-design/pro-flow/assets/155069388/1b1f200c-c329-4656-94ec-df89599f488f)

![image](https://github.com/ant-design/pro-flow/assets/155069388/ed5b114b-839b-4f6e-8598-2dfab52fb53e)

**Comment by ModestFun** [comment]
try version 1.0.1. fixed.

**Comment by ModestFun** [comment]
try version 1.0.1. fixed.
