### ISSUE TITLE
关于和 XFlow 的区别 🤔️

### ISSUE THREAD

**Issue by CasoMemory** [ant-design/pro-flow#74]
### 🧐 问题描述

由于最近也在调研流程图相关的一些能力，目前比较好奇，ProFlow 与 [XFlow](https://xflow.antv.vision/docs/tutorial/solutions/flow) 的一些具体区别，以及各自对应的具体应用场景是哪些？

**Comment by fnoopv** [comment]
XFlow 基于 X6, ProFlow 基于 ReactFlow

**Comment by arvinxx** [comment]
> XFlow 基于 X6, ProFlow 基于 ReactFlow

正解。

此外，功能层面，我们更加面向业务应用，符合 antd 的设计规范，和 antd 的主题系统一脉相承（譬如直接兼容 antd 的主题切换能力等）。 xflow 则是用的 AntV 的规范。

同时，由于我们基于 react-flow 实现，因此 api 风格更接近 react 原生应用，并提供了 `useFlowView` 等的一系列 hooks。使用起来心智上会更加简单一些。

但我们目前没有提供一些常见图场景的模板 demo（譬如 XFlow 中已经提供的 DAG、流程图 等），这些是 XFlow 中已经做得比较完善的地方。如果使用 ProFlow，你目前仍然需要手动实现。

**Comment by CasoMemory** [comment]
> > XFlow 基于 X6, ProFlow 基于 ReactFlow
> 
> 正解。
> 
> 此外，功能层面，我们更加面向业务应用，符合 antd 的设计规范，和 antd 的主题系统一脉相承（譬如直接兼容 antd 的主题切换能力等）。 xflow 则是用的 AntV 规范。
> 
> 同时，由于我们基于 react-flow 实现，因此 api 风格更接近 react 原生应用，并提供了 `useFlowView` 等的一系列 hooks。使用起来心智上会更加简单一些，DX 和 UX 也会更好。
> 
> 但我们目前没有提供一些常见图场景的模板 demo（譬如 XFlow 中已经提供的 DAG、流程图 等），这些是 XFlow 中已经做得比较完善的地方。如果使用 ProFlow，目前仍然需要手动实现。

感谢耐心解答。

反馈一个站点示例问题（不确定是不是 bug），在[数据受控](https://pro-flow.antdigital.dev/guide/flow-editor#%E6%95%B0%E6%8D%AE%E5%8F%97%E6%8E%A7)例子下，点击「新增节点」按钮添加多个节点后，选中一个节点执行删除交互，再点击「新增节点」按钮后，无任何响应。

 期待 ProFlow 后续提供更多的便捷能力。

**Comment by ModestFun** [comment]
> 反馈一个站点示例问题（不确定是不是 bug），在[数据受控](https://pro-flow.antdigital.dev/guide/flow-editor#%E6%95%B0%E6%8D%AE%E5%8F%97%E6%8E%A7)例子下，点击「新增节点」按钮添加多个节点后，选中一个节点执行删除交互，再点击「新增节点」按钮后，无任何响应。

已在最新版本修复
