### ISSUE TITLE
🐛[BUG] BasicGroupNode 没有导出

### ISSUE THREAD

**Issue by fnoopv** [ant-design/pro-flow#76]
### 🐛 bug 描述

使用 `import { BasicGroupNode } from '@ant-design/pro-flow';` 导入 `BasicGroupNode` 时提示没有此导出成员

### 🏞 期望结果

能正常导入

### © 版本信息

- pro-flow-editor 版本: [e.g. 1.0.0]  1.1.0
- 浏览器环境 linux kde chrome 120
- 开发环境 [e.g. mac OS]

**Comment by ModestFun** [comment]
最新版本已修复
