### ISSUE TITLE
🐛[BUG] FlowEditor在节点为空时会一直处于画布初始化状态，导出无法渲染空画布

### ISSUE THREAD

**Issue by fnoopv** [ant-design/pro-flow#79]
### 🐛 bug 描述

新建FlowEditor时，如果没有节点，则会一直处于画布初始化状态，导致无法初始化一个空画布。源码中是用的`useNodesInitialized` 获取节点加载完成的状态，并根据这个状态区渲染加载中还是画布。但是这个hooks官网说没有节点时始终返回`false`，导致没有节点时一直处于画布加载中的状态
官网文档: https://reactflow.dev/api-reference/hooks/use-nodes-initialized#notes

### 📷 复现步骤

官网任意一个 `FlowEditor` 的demo去掉其中的 `useEffect` 添加节点的代码即可

### 🏞 期望结果

FlowEditor在没有节点时能正常渲染画布

### 💻 复现代码

[可复现 demo](https://codesandbox.io/s/html2ksetch-demo-m53be?file=/src/Demo.tsx)

### © 版本信息

- pro-flow-editor 版本: [e.g. 1.0.0] 1.2.1
- 浏览器环境 chrome 120
- 开发环境 [e.g. mac OS] linux kde

**Comment by ModestFun** [comment]
1.2.2 版本已修复
