### ISSUE TITLE
🧐[问题] 自定义节点时参数问题

### ISSUE THREAD

**Issue by fnoopv** [ant-design/pro-flow#80]
### 🧐 问题描述

reactflow 自定义节点时会会有一个 `NodeProps` 的类型别名，可以通过这个类型别名明确参数。但是 ProFlow 并没有导出这个类型别名，可以导出这个类型别名吗？如果 `NodeProps` 不符合 `ProFlow` 的参数要求，那么有没有别的类型别名可以用于定义自定义组件的参数？或者自定义组件这部分给出指导？

**Comment by arvinxx** [comment]
参数我记得不是完全一样的 @ModestFun 你看看？ 对应节点的props应该是需要的，而且我记得也有

**Comment by ModestFun** [comment]
> ### 🧐 问题描述
> reactflow 自定义节点时会会有一个 `NodeProps` 的类型别名，可以通过这个类型别名明确参数。但是 ProFlow 并没有导出这个类型别名，可以导出这个类型别名吗？如果 `NodeProps` 不符合 `ProFlow` 的参数要求，那么有没有别的类型别名可以用于定义自定义组件的参数？或者自定义组件这部分给出指导？
> 
> ### 💻 示例代码
> ### 🚑 其他信息

<img width="451" alt="image" src="https://github.com/ant-design/pro-flow/assets/61576426/2b292eb9-8454-4ade-a6ac-b26f91795321">
这样的使用方式可以满足你的需求吗？

**Comment by ModestFun** [comment]
1.2.2 版本已修复。现在可以导出 NodeProps 使用了
