### ISSUE TITLE
🧐[问题] Antd 4.x的项目无法使用吗

### ISSUE THREAD

**Issue by wooktao** [ant-design/pro-flow#86]
### 🧐 问题描述
使用umimax+antd4的cli
无法使用proflow  直接工程报错
### 💻 示例代码

依赖情况：
"dependencies": {
    "@ant-design/charts": "^1.4.3",
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "1.1.1",
    "@ant-design/pro-flow": "^1.2.2",
    "@umijs/route-utils": "^2.0.0",
    "@wangeditor/editor": "^5.1.23",
    "@wangeditor/editor-for-react": "^1.0.6",
    "ahooks": "^3.7.8",
    "antd": "^4.20.0",
    "classnames": "^2.3.0",
    "dagre": "^0.8.5",
    "intro.js": "^7.2.0",
    "intro.js-react": "^1.0.0",
    "lodash": "^4.17.0",
    "moment": "^2.29.0",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.1.0",
    "rc-util": "^5.16.0",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.7.0",
    "react-dom": "^17.0.0",
    "react-flow-renderer": "^10.3.17",
    "react-form-simple": "^1.4.1",
    "react-helmet-async": "^1.2.0",
    "umi": "^3.5.0"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.1.0",
    "@playwright/test": "^1.17.0",
    "@types/classnames": "^2.3.1",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.0",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.0",
    "@types/react": "^18.2.35",
    "@types/react-dom": "^18.2.14",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.11.1",
    "@umijs/openapi": "^1.6.0",
    "@umijs/plugin-blocks": "^2.2.0",
    "@umijs/plugin-esbuild": "^1.4.0",
    "@umijs/plugin-openapi": "^1.3.3",
    "@umijs/preset-ant-design-pro": "^1.3.0",
    "@umijs/preset-dumi": "^1.1.0",
    "@umijs/preset-react": "^2.1.0",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.3.0",
    "detect-installer": "^1.0.0",
    "eslint": "^7.32.0",
    "gh-pages": "^3.2.0",
    "husky": "^7.0.4",
    "jsdom-global": "^3.0.0",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.1.0",
    "prettier": "^2.5.0",
    "stylelint": "^13.0.0",
    "swagger-ui-dist": "^4.12.0",
    "typescript": "^4.5.0",
    "umi-serve": "^1.9.10"
  },
### 🚑 其他信息

![screenshot-20240223-183621](https://github.com/ant-design/pro-flow/assets/80517693/651e7381-aa5b-41de-851e-cdcdd4e8eb02)

**Comment by arvinxx** [comment]
不支持v4，请使用antd v5

**Comment by wooktao** [comment]
@arvinxx 
![image](https://github.com/ant-design/pro-flow/assets/80517693/5b66a36b-127f-4497-8640-b7265001d81c)
已升级v5但是还是有问题

**Comment by arvinxx** [comment]
@wooktao 试试清理下 node_modules 后重试

**Comment by wooktao** [comment]
@arvinxx  搞了一下午 应该是cli的配置问题  我用的基于umi3的antdpro2  太老了 很多地方有工程问题 改工程成本太大了 只能分两个包了
