### ISSUE TITLE
🧐[问题] 添加edge调用setEdges报错

### ISSUE THREAD

**Issue by justb** [ant-design/pro-flow#95]
### 🧐 问题描述
第一次设置edge没问题，后续添加边报错，页面上无法正常显示该边
![image](https://github.com/ant-design/pro-flow/assets/22002343/00a8a1c0-3f11-4364-99ea-957ca36ba260)

### 💻 示例代码

![image](https://github.com/ant-design/pro-flow/assets/22002343/adc4ed19-53d4-454f-90fc-0ffa24164827)

**Comment by ModestFun** [comment]
信息太少，没法判断，可以加一下群，详聊一下
<img width="385" alt="image" src="https://github.com/ant-design/pro-flow/assets/61576426/f4a59d07-bd9b-45d4-9171-ebe9117303b7">
